service: import-service

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-north-1
  stage: dev
  httpApi:
    cors: true
    id: h7x67x6ia8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:ListBucket
      Resource: "arn:aws:s3:::product-service-dev-serverlessdeploymentbucket-zaa6fmhns43p/*"

functions:
  importProductsFile:
    handler: importProductsFile.handler
    events:
      - httpApi:
          method: get
          path: /import
          cors: true
  importFileParser:
    handler: importFileParser.handler
    events:
      - s3:
          bucket: product-service-dev-serverlessdeploymentbucket-zaa6fmhns43p  
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
