service: import-service

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-north-1
  stage: dev
  httpApi:
    id: h7x67x6ia8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:ListBucket
      Resource: "arn:aws:s3:::import-service-uploaded/*"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - httpApi:
          method: get
          path: /import
          request:
            parameters:
              querystrings:
                name: true 
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: your-bucket-name
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
